/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.worldwindearth;

import gov.nasa.worldwind.WorldWind;
import gov.nasa.worldwind.cache.FileStore;
import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.osmbuildings.OSMBuildingsLayer;
import org.tinyrcp.App;
import org.tinyrcp.TinyFactory;

/**
 *
 * @author sbodmer
 */
public class JAbout extends javax.swing.JDialog implements HyperlinkListener {

    /**
     * Creates new form JAbout
     */
    public JAbout(java.awt.Frame parent, boolean modal, App app) {
        super(parent, modal);

        initComponents();

        String txt = "";
        ArrayList<String> cont = new ArrayList<>();
        ArrayList<TinyFactory> factories = app.getFactories(null);
        for (int i = 0;i < factories.size();i++) {
            TinyFactory fac = factories.get(i);
            String author = (String) fac.getProperty(TinyFactory.PROPERTY_AUTHOR);
            if (author == null) continue;
            if (!cont.contains(author)) {
                txt += "" + author + "\n";
                cont.add(author);
            }

        }
        TA_Contributors.setText(txt);
        TA_Contributors.setCaretPosition(0);

        try {
            FileStore fs = WorldWind.getDataFileStore();
            List<? extends File> list = fs.getLocations();
            StringBuilder b = new StringBuilder("");
            b.append("WorldWind cache paths\n");
            for (int i = 0;i < list.size();i++) {
                File files = list.get(i);
                b.append(" " + files.getPath() + " (exists=" + files.exists() + ")\n");
            }
            TA_Paths.setText(b.toString());

        } catch (NullPointerException ex) {
            ex.printStackTrace();
        }

        TP_WorldWind.addHyperlinkListener(this);

        try {
            URL url = getClass().getResource("/app/Resources/CHANGELOG.TXT");
            TP_ChangeLog.setPage(url);
            TP_ChangeLog.setCaretPosition(0);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    //**************************************************************************
    //*** HyperlinkListener
    //**************************************************************************
    @Override
    public void hyperlinkUpdate(HyperlinkEvent e) {
        if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                Desktop dt = Desktop.getDesktop();
                dt.browse(e.getURL().toURI());

            } catch (Exception ex) {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Image = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP_WorldWind = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA_Contributors = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Paths = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TP_ChangeLog = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 480));

        LB_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/worldwindearth/Resources/Images/cards_wwe.jpg"))); // NOI18N
        getContentPane().add(LB_Image, java.awt.BorderLayout.CENTER);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(145, 200));

        TP_WorldWind.setEditable(false);
        TP_WorldWind.setContentType("text/html"); // NOI18N
        TP_WorldWind.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        TP_WorldWind.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      This application uses the Nasa WorldWind SDK<br>\n      <a href=\"https://worldwind.arc.nasa.gov\">Nasa worldwind home page</a>\n    </p>\n  </body>\n</html>\n");
        jScrollPane2.setViewportView(TP_WorldWind);

        jTabbedPane1.addTab("WorldWind", jScrollPane2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        TA_Contributors.setEditable(false);
        TA_Contributors.setColumns(20);
        TA_Contributors.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        TA_Contributors.setRows(5);
        jScrollPane3.setViewportView(TA_Contributors);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Contributors", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        TA_Paths.setEditable(false);
        TA_Paths.setColumns(20);
        TA_Paths.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        TA_Paths.setRows(5);
        jScrollPane1.setViewportView(TA_Paths);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Paths", jPanel2);

        TP_ChangeLog.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jScrollPane5.setViewportView(TP_ChangeLog);

        jTabbedPane1.addTab("ChangeLog", jScrollPane5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.SOUTH);

        jPanel3.setBackground(new java.awt.Color(144, 202, 249));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("<html>\n<b>JWorldWindEarth</b> Preview<br>\n</html>");
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        setBounds(0, 0, 650, 510);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Image;
    private javax.swing.JTextArea TA_Contributors;
    private javax.swing.JTextArea TA_Paths;
    private javax.swing.JTextPane TP_ChangeLog;
    private javax.swing.JTextPane TP_WorldWind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
