/*
 * JWorldWindLayerCellRenderer.java
 *
 * Created on June 7, 2007, 11:03 AM
 */
package org.worldwindearth;

import gov.nasa.worldwind.layers.Layer;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import org.tinyrcp.App;
import org.tinyrcp.TinyFactory;

/**
 *
 * @author sbodmer
 */
public class JWWEPluginCellRenderer extends javax.swing.JPanel implements TableCellRenderer {

    App app = null;

    /**
     *
     */
    public JWWEPluginCellRenderer(App app) {
        this.app = app;

        initComponents();
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Color fg = isSelected?table.getSelectionForeground():table.getForeground();
        LB_Name.setForeground(fg);
        
        Layer l = (Layer) value;
        LB_Name.setText("");
        LB_Name.setIcon(null);
        
        if (l != null) {
            LB_Name.setText(l.getName());
            WWEPlugin p = (WWEPlugin) l.getValue(WWEPlugin.AVKEY_WORLDWIND_LAYER_PLUGIN);
            if (p != null) {
                LB_Icon.setIcon(p.getPluginFactory().getFactoryIcon(TinyFactory.ICON_SIZE_NORMAL));
                LB_Name.setName(p.getPluginName());
            }
            
        }
        
        if (isSelected) {
            setBackground(table.getSelectionBackground());

        } else {
            setBackground(table.getBackground());
        }
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Icon = new javax.swing.JLabel();
        LB_Name = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        LB_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Icon.setIconTextGap(0);
        LB_Icon.setMaximumSize(new java.awt.Dimension(30, 30));
        LB_Icon.setMinimumSize(new java.awt.Dimension(30, 30));
        LB_Icon.setPreferredSize(new java.awt.Dimension(30, 30));
        add(LB_Icon, java.awt.BorderLayout.WEST);

        LB_Name.setText("Name");
        LB_Name.setMinimumSize(new java.awt.Dimension(0, 10));
        add(LB_Name, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Icon;
    private javax.swing.JLabel LB_Name;
    // End of variables declaration//GEN-END:variables

}
