/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.worldwindearth.geocode;

import gov.nasa.worldwind.geom.Position;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import org.worldwindearth.components.layers.ScreenProjectionLayer;
import org.worldwindearth.components.layers.ScreenProjectionLayer.ScreenProjectable;

/**
 * Wrapper for a screen projectable object
 * 
 * @author sbodmer
 */
public class JBalloon extends javax.swing.JPanel implements ScreenProjectionLayer.ScreenProjectable {
    static final Color BACKGROUND = new Color(255,255,255,128);

    ScreenProjectable proj = null;
    
    /**
     * Creates new form JReverse
     * @param proj
     * @param r
     */
    public JBalloon(ScreenProjectable proj, URL icon) {
        this.proj = proj;
        
        initComponents();
        
        LB_Balloon.setIcon(new ImageIcon(icon));
        LB_Summary.setText(" "+proj.getProjectableName());
        LB_Summary.setBackground(BACKGROUND);
        LB_Summary.setVisible(proj.getProjectableName().equals("")?false:true);
        LB_Balloon.setToolTipText(proj.getProjectableName());
    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    @Override
    public String toString() {
        return proj.toString();
    }
    
    public ScreenProjectable getScreenProjectable() {
        return proj;
    }
    
    //**************************************************************************
    //*** ScreenProjectionLayer.ScreenProjectable
    //**************************************************************************
    @Override
    public Position getProjectablePosition() {
        return proj.getProjectablePosition();
    }
    
    @Override
    public String getProjectableName() {
        return proj.getProjectableName();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Balloon = new javax.swing.JLabel();
        LB_Summary = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        LB_Balloon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/worldwindearth/geocode/Resources/Icons/32x32/BalloonBlue.png"))); // NOI18N
        add(LB_Balloon, java.awt.BorderLayout.WEST);

        LB_Summary.setText("...");
        LB_Summary.setOpaque(true);
        add(LB_Summary, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel LB_Balloon;
    protected javax.swing.JLabel LB_Summary;
    // End of variables declaration//GEN-END:variables

    
}
