/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.worldwindearth.models;

import org.osmbuildings.*;
import gov.nasa.worldwind.WorldWind;
import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.cache.FileStore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.tinyrcp.App;
import org.tinyrcp.TinyPlugin;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.worldwindearth.WWEFactory;

/**
 *
 *
 * @author sbodmer
 */
public class JModelsWWEFactory extends javax.swing.JPanel implements WWEFactory, ActionListener {

    App app = null;

    /**
     * Creates new form OSMBuildingsWWELayerPluginFactory
     */
    public JModelsWWEFactory() {

        initComponents();

    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    //**************************************************************************
    //*** WWEPluginFactory
    //**************************************************************************
    @Override
    public Icon getFactoryIcon(int size) {
        return LB_Name.getIcon();
    }

    @Override
    public String getFactoryName() {
        return LB_Name.getText();
    }

    @Override
    public String getFactoryDescription() {
        return LB_Description.getText();
    }

    @Override
    public String getFactoryCategory() {
        return PLUGIN_CATEGORY_WORLDWIND_LAYER;
    }

    @Override
    public String getFactoryFamily() {
        return PLUGIN_FAMILY_WORLDWIND_LAYER_BUILDINGS;
    }

    @Override
    public JComponent getFactoryConfigComponent() {
        return this;
    }

    @Override
    public void initialize(App app) {
        this.app = app;

    }

    @Override
    public void configure(Element config) {
        if (config == null) return;

    }

    @Override
    public TinyPlugin newPlugin(Object o) {
        return new JModelsWWEPlugin(this, (WorldWindow) o);
    }

    @Override
    public void store(Element config) {
        if (config == null) return;

    }

    @Override
    public void destroy() {
        //---
    }

    @Override
    public Object getProperty(String property) {
        return null;
    }

    public boolean doesFactorySupport(Object obj) {
        if (obj != null) {
            if (obj.toString().equals(WWEFactory.PLANET_EARTH)) return true;
            // if (obj.toString().equals(WWEFactory.PLANET_EARTH)) return true;
        }
        return false;
    }

    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Name = new javax.swing.JLabel();
        LB_Description = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        LB_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/worldwindearth/models/Resources/Icons/22x22/models.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/worldwindearth/models/Models"); // NOI18N
        LB_Name.setText(bundle.getString("factory_name")); // NOI18N

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel LB_Description;
    protected javax.swing.JLabel LB_Name;
    protected javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //**************************************************************************
    //*** Private
    //**************************************************************************
   

}
