/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.worldwindearth.components.renderers;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.tinyrcp.App;
import org.worldwindearth.components.Camera;

/**
 *
 * @author sbodmer
 */
public class JCameraCellRenderer extends javax.swing.JPanel implements ListCellRenderer<Camera> {

    App app = null;
    
    /**
     * Creates new form JCameraCellRenderer
     */
    public JCameraCellRenderer(App app) {
        this.app = app;
        
        initComponents();
    }

    //**************************************************************************
    //*** ListCellRenderer
    //**************************************************************************
    @Override
    public Component getListCellRendererComponent(JList list, Camera value, int index, boolean isSelected, boolean cellHasFocus) {
        LB_Title.setText(value.getTitle());
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Icon = new javax.swing.JLabel();
        LB_Title = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LB_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Icon.setPreferredSize(new java.awt.Dimension(64, 64));
        add(LB_Icon);

        LB_Title.setText("...");
        add(LB_Title);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Icon;
    private javax.swing.JLabel LB_Title;
    // End of variables declaration//GEN-END:variables

    
}
