/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.nasa.stars;

import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.layers.Layer;
import gov.nasa.worldwind.layers.StarsLayer;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import org.tinyrcp.App;
import org.w3c.dom.Element;
import org.worldwindearth.WWEFactory;
import org.worldwindearth.WWEFactory;
import org.worldwindearth.WWEPlugin;

/**
 * Stars dome
 * 
 * @author sbodmer
 */
public class JStarsWWEPlugin extends JPanel implements WWEPlugin, ActionListener {
    App app = null;
    WWEFactory factory = null;
    WorldWindow ww = null;
    
    StarsLayer layer = new StarsLayer();
    
    /**
     * Creates new form JTerminalsLayer
     */
    public JStarsWWEPlugin(WWEFactory factory, WorldWindow ww) {
        super();
        this.factory = factory;
        this.ww = ww;
        
        initComponents();
        
       
    }

    
    
    //**************************************************************************
    //*** Plugin
    //**************************************************************************
    

    @Override
    public String getPluginName() {
        return layer.getName();
    }
    
    @Override
    public void setPluginName(String name) {
        layer.setName(name);
    }
    
    @Override
    public JComponent getVisualComponent() {
        return null;
    }
    
    @Override
    public JComponent getConfigComponent() {
        return null;
    }

    @Override
    public WWEFactory getPluginFactory() {
        return factory;
    }

    @Override
    public void setup(App app, Object arg) {
        this.app = app;
        
        layer.setName("Stars");
        layer.setValue(AVKEY_WORLDWIND_LAYER_PLUGIN, this);
    }

    @Override
    public void configure(Element config) {
        //---
        
    }
    
    @Override
    public void cleanup() {
        layer.dispose();
        
    }

    @Override
    public void saveConfig(Element config) {
        //---
    }

    @Override
    public Object getProperty(String property) {
        return null;
    }

    @Override
    public void setProperty(String property, Object value) {
        //---
    }

    @Override
    public Object doAction(String action, Object argument) {
        return null;
    }

    //**************************************************************************
    //*** WorldWindLayerPlugin
    //**************************************************************************
    @Override
    public Layer getLayer() {
        return layer;
    }
    
    @Override
    public JToggleButton getLayerButton() {
        return null;
    }
    
    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        //---
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
