/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.worldwindearth.wms;

import gov.nasa.worldwind.ogc.wms.WMSLayerCapabilities;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author sbodmer
 */
public class WMSLayerCapabilitiesCellRenderer extends javax.swing.JPanel implements TableCellRenderer {

    /**
     * Creates new form WMSLayerCapabilitiesCellRenderer
     */
    public WMSLayerCapabilitiesCellRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Title = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        LB_Title.setText("...");
        add(LB_Title, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        WMSLayerCapabilities cap = (WMSLayerCapabilities) value;
        LB_Title.setText(cap.getTitle());
        if (isSelected) {
            setBackground(table.getSelectionBackground());
            
        } else {
            setBackground(table.getBackground());
        }
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel LB_Title;
    // End of variables declaration//GEN-END:variables
}
