/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.worldwindearth.components.layers.buildings;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author sbodmer
 */
public class JBuildingsProviderDlg extends javax.swing.JDialog implements ActionListener {

    BuildingsProvider provider = null;

    public static JBuildingsProviderDlg newDialog(Container parent, BuildingsProvider provider) {
        if (parent instanceof JFrame) {
            return new JBuildingsProviderDlg((JFrame) parent, provider);

        } else if (parent instanceof JDialog) {
            return new JBuildingsProviderDlg((JDialog) parent, provider);
            
        } else {
            return new JBuildingsProviderDlg(provider);
        }
    }

    /**
     * Creates new form JBuidlingFrm
     */
    public JBuildingsProviderDlg(JFrame parent, BuildingsProvider provider) {
        super(parent, true);

        this.provider = provider;

        initComponents();

        init();
    }

    public JBuildingsProviderDlg(JDialog parent, BuildingsProvider provider) {
        super(parent, true);

        this.provider = provider;

        initComponents();

        init();
    }
    
    public JBuildingsProviderDlg(BuildingsProvider provider) {
        super();
        setModal(true);

        this.provider = provider;

        initComponents();

        init();
    }
    
    private void init() {
        TF_Title.setText(provider.getTitle());
        TF_Url.setText(provider.getUrl());
        SP_MinLevel.setValue(provider.getMinLevel());
        SP_MaxLevel.setValue(provider.getMaxLevel());

        BT_Ok.addActionListener(this);
        BT_Cancel.addActionListener(this);
    }
    /**
     * Return the original (updated) provider or null if canceled
     *
     * @return
     */
    public BuildingsProvider getProvider() {
        return provider;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_ProviderData = new javax.swing.JPanel();
        TF_Title = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_Url = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SP_MinLevel = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        SP_MaxLevel = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        BT_Ok = new javax.swing.JButton();
        BT_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TF_Title.setText("Buildings servers");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Title");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 26));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("URL");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 26));

        TF_Url.setText("http://");
        TF_Url.setToolTipText("<html>\nThe building xml file provider, the following sequence will be replaced\n<table>\n<tr><td>${Z}</td><td>The zoom level (ex. 15)</td></tr>\n<tr><td>${X}</td><td>The X tile column</td></tr>\n<tr><td>${Y}</td><td>The Y tile row</td></tr>\n</table>\nTo have random server use \"[ab...]\" notation, which will use a or b or ... in a random way.<br>\nEx: http://[abcd].les-studios-inexistants.ch/buildings/${Z}/${X}/${Y}/buildings.xml\n</html>");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Min level");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 26));

        SP_MinLevel.setModel(new javax.swing.SpinnerNumberModel(15, 14, 18, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Max Level");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 26));

        SP_MaxLevel.setModel(new javax.swing.SpinnerNumberModel(15, 14, 20, 1));

        javax.swing.GroupLayout PN_ProviderDataLayout = new javax.swing.GroupLayout(PN_ProviderData);
        PN_ProviderData.setLayout(PN_ProviderDataLayout);
        PN_ProviderDataLayout.setHorizontalGroup(
            PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ProviderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_ProviderDataLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PN_ProviderDataLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SP_MinLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PN_ProviderDataLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SP_MaxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PN_ProviderDataLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_Url, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PN_ProviderDataLayout.setVerticalGroup(
            PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ProviderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_MinLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PN_ProviderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_MaxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PN_ProviderData, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BT_Ok.setText("Ok");
        jPanel1.add(BT_Ok);

        BT_Cancel.setText("Cancel");
        BT_Cancel.setActionCommand("cancel");
        jPanel1.add(BT_Cancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();

    }//GEN-LAST:event_formWindowClosing

    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == BT_Ok) {
            provider.setTitle(TF_Title.getText().trim());
            provider.setUrl(TF_Url.getText().trim());
            provider.setMinLevel((int) SP_MinLevel.getValue());
            provider.setMaxLevel((int) SP_MaxLevel.getValue());
            close();

        } else if (e.getSource() == BT_Cancel) {
            provider = null;
            close();

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BT_Cancel;
    protected javax.swing.JButton BT_Ok;
    protected javax.swing.JPanel PN_ProviderData;
    protected javax.swing.JSpinner SP_MaxLevel;
    protected javax.swing.JSpinner SP_MinLevel;
    protected javax.swing.JTextField TF_Title;
    protected javax.swing.JTextField TF_Url;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        setVisible(false);
        dispose();
    }

}
